spring:
  datasource:
    url: jdbc:mysql://8.138.114.27:3306/mayer-cms?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: mayer-cms
    password: hF6JHMamwFbdNmM8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      path: /api/v1
