spring:
  profiles:
    active: dev
  application:
    name: Markdown-CMS
  main:
    banner-mode: console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off
  type-aliases-package: org.common.entity # 扫描的类型别名包
  mapper-locations: classpath:mapper/*.xml # 映射文件的位置

server:
  servlet:
    context-path: /api # 根路径前缀
  shutdown: graceful