spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
    username: root
    password: mayer964553
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.yourpackage.entity
  mapper-locations: classpath:mapper/*.xml
